language: python
cache: pip
dist: bionic

python:
# - 3.6
- 3.7

addons:
  postgresql: '10'

before_install:
  - sudo apt-get -qq update

install:
- pip install --upgrade pip setuptools wheel
- pip install -e .
- pip install -r requirements/dev.txt

before_script:
- cp .env.travis .env
- createdb test_isimip_metadata

script:
- pytest --cov=isimip_publisher

# after_success:
# - coveralls
