language: python
cache: pip
dist: bionic

python:
- 3.7
- 3.8

addons:
  postgresql: '10'

env:
  global:
  - LOG_LEVEL=DEBUG
  - LOG_FILE=isimip-publisher.log
  - REMOTE_DEST=localhost
  - REMOTE_DIR=${PWD}/testing/files/
  - LOCAL_DIR=${PWD}/testing/work/
  - PUBLIC_DIR=${PWD}/testing/public/
  - ARCHIVE_DIR=${PWD}/testing/archive/
  - DATACITE_DIR=${PWD}/testing/datacite/
  - DATABASE=postgresql+psycopg2://@/test_isimip_metadata
  - PROTOCOL_LOCATIONS=${PWD}/testing/protocol/
  - ISIMIP_DATA_URL=http://localhost:8000/
  jobs:
  - MOCK=True
  - MOCK=False

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libproj-dev libgeos++-dev
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -C "" -q
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts

install:
- pip install --upgrade pip setuptools wheel
- pip install -e .
- pip install -r requirements/dev.txt
- pip uninstall -y shapely
- "pip install --no-binary :all: shapely"
- pip install coveralls

before_script:
- createdb test_isimip_metadata
- psql test_isimip_metadata -c 'CREATE EXTENSION pg_trgm;'

script:
- pytest --cov=isimip_publisher

after_success:
- coveralls
