language: python
cache: pip
dist: bionic

python:
- 3.6
- 3.7
- 3.8

addons:
  postgresql: '10'

before_install:
  - sudo apt-get -qq update
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -q
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts

install:
- pip install --upgrade pip setuptools wheel
- pip install -e .
- pip install -r requirements/dev.txt
- pip install coveralls

before_script:
- cp .env.travis .env
- createdb test_isimip_metadata

script:
- pytest --cov=isimip_publisher

after_success:
- coveralls
