[project]
name = "isimip-publisher"
authors = [
    { name = "Jochen Klar", email = "jochen.klar@pik-potsdam.de" },
]
maintainers = [
    { name = "Jochen Klar", email = "jochen.klar@pik-potsdam.de" },
]
description = "A command line tool to publish climate impact data from the ISIMIP project."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
classifiers = [
    'Operating System :: OS Independent',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
dependencies = [
    "datacite>=1.1.2",
    "isimip-utils>=1.2",
    "jsonschema>=3.2.0",
    "netCDF4>=1.5.6",
    "psycopg2-binary>=2.8.6",
    "python-dotenv==0.16.0",
    "requests>=2.25.1",
    "SQLAlchemy>=1.4.2",
    "tqdm>=4.59.0",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/ISI-MIP/isimip-publisher"

[project.optional-dependencies]
pytest = [
    "pytest~=7.4.0",
    "pytest-console-scripts~=1.4.1",
    "pytest-cov~=4.1.0",
]

[project.scripts]
isimip-publisher = "isimip_publisher.main:main"

[tool.setuptools]
packages = ["isimip_publisher"]

[tool.setuptools.dynamic]
version = { attr = "isimip_publisher.__version__" }

[tool.pytest.ini_options]
python_files = "test_*.py"
script_launch_mode = "subprocess"
