dirname_pattern: |
  (?P<sector>[a-z0-9-._]+)/
  (?P<model>[A-Za-z0-9-.]+)$

filename_pattern: |
  ^(?P<modelname>[a-z0-9-.]+)
  _(?P<alpha>[a-z0-9-]+)
  _(?P<beta>[a-z0-9-.]+)
  _(?P<gamma>[a-z0-9-.]+)
  _(?P<delta>[a-z0-9-.]+)
  _(?P<var>[a-z0-9-.]+)
  _(?P<region>[a-z0-9-]+)
  _(?P<timestep>[a-z0-9-.]+)
  _(?P<start_year>\d{4})
  _(?P<end_year>\d{4})

dataset_pattern: |
  ^(?P<modelname>[a-z0-9-.]+)
  _(?P<alpha>[a-z0-9-]+)
  _(?P<beta>[a-z0-9-.]+)
  _(?P<gamma>[a-z0-9-.]+)
  _(?P<delta>[a-z0-9-.]+)
  _(?P<var>[a-z0-9-.]+)
  _(?P<region>[a-z0-9-]+)
  _(?P<timestep>[a-z0-9-.]+)

alpha_validation:
- lorem
- ipsum
