egg: spam

templates:
  eggspam: '%(egg)s is spam!'

netcdf_metadata_keep:
- Conventions
- contact
- institution

netcdf_metadata:
- version

json_metadata:
- simulation_round
- product
- sector
- model
- a
- b
- c
- d

dataset_metadata:
- simulation_round
- product
- sector
- model
- a
- b
- c
- d

file_metadata:
- simulation_round
- product
- sector
- model
- a
- b
- c
- d

database_metadata_search:
- simulation_round
- product
- sector
