egg: spam

templates:
  eggspam: '%(egg)s is spam!'

netcdf_metadata_keep:
- Conventions
- contact
- institution

netcdf_metadata:
- version

dataset_metadata:
- simulation_round
- product
- sector
- model
- alpha
- beta
- gamma
- delta
- epsilon

file_metadata:
- simulation_round
- product
- sector
- model
- alpha
- beta
- gamma
- delta
- epsilon

database_metadata_search:
- simulation_round
- product
- sector
