egg: spam

templates:
  eggspam: '%(egg)s is spam!'

netcdf_metadata:
- simulation_round
- sector
- model
- version

json_metadata:
- simulation_round
- sector
- model
- a
- b
- c
- d

dataset_metadata:
- simulation_round
- sector
- model
- a
- b
- c
- d

file_metadata:
- simulation_round
- sector
- model
- a
- b
- c
- d
