name: pytest

on:
  push:
    branches:
    - main
    - test
    tags:
    - "*"
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: read

env:
  PYTHONDONTWRITEBYTECODE: 1
  FORCE_COLOR: 1
  PYTHON_VERSION: "3.13"

jobs:
  pytest:
    name: Run tests 🧪
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mock: [true, false]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repo 🛎️
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Set up Python 🐍
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: pip

    - name: Set up ssh 🛜
      run: |
        ssh-keygen -t rsa -f ~/.ssh/id_rsa -N "" -C "" -q
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
        ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
        ssh localhost

    - name: Install package 📦
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install coveralls
        python3 -m pip install -e .
        python3 -m pip install -e .[pytest]

    - name: Prepare database 🗄️
      run: |
        psql postgres://postgres:postgres_password@localhost -c 'CREATE DATABASE test_isimip_metadata;'
        psql postgres://postgres:postgres_password@localhost/test_isimip_metadata -c 'CREATE EXTENSION pg_trgm;'

    - name: Setup environment file 🏞️
      run: |
        echo "ISIMIP_LOG_LEVEL=DEBUG" >> $GITHUB_ENV
        echo "ISIMIP_LOG_FILE=isimip-publisher.log" >> $GITHUB_ENV
        echo "ISIMIP_REMOTE_DEST=localhost" >> $GITHUB_ENV
        echo "ISIMIP_REMOTE_DIR=${GITHUB_WORKSPACE}/testing/remote/" >> $GITHUB_ENV
        echo "ISIMIP_LOCAL_DIR=${GITHUB_WORKSPACE}/testing/local/" >> $GITHUB_ENV
        echo "ISIMIP_PUBLIC_DIR=${GITHUB_WORKSPACE}/testing/public/" >> $GITHUB_ENV
        echo "ISIMIP_ARCHIVE_DIR=${GITHUB_WORKSPACE}/testing/archive/" >> $GITHUB_ENV
        echo "ISIMIP_DATABASE=postgresql+psycopg2://postgres:postgres_password@localhost/test_isimip_metadata" >> $GITHUB_ENV
        echo "ISIMIP_PROTOCOL_LOCATIONS=${GITHUB_WORKSPACE}/testing/protocol/" >> $GITHUB_ENV
        echo "ISIMIP_DATA_URL=http://localhost:8000/" >> $GITHUB_ENV
        echo "ISIMIP_MOCK=${{ matrix.mock }}" >> $GITHUB_ENV

    - name: Run pytest 🧪
      run: |
        pytest --cov=isimip_publisher
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: "${{ env.PYTHON_VERSION }}-mock-${{ matrix.mock }}"
        COVERALLS_PARALLEL: true

  coveralls:
    needs: pytest
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Run coveralls finish
      run: |
        pip install coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
